name: readme-scribe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: muesli/readme-scribe@v0.1
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      -
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        if: github.event_name != 'pull_request'
        with:
          commit_message: 'Update generated README'
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
